name: CI

on:
  workflow_dispatch:
  release:
    types: [unpublished]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v2
        
      - name: Restore
        run: npm i
        
      - name: Build & Package
        run: npm run package
        
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: ./bin/squirrel-windows/*
